In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("flood.csv")

In [4]:
df.head()

   Unnamed: 0  Rainfall (mm)  ...  Flood Occurred  Risk_encoded
0           0     218.999493  ...               1             4
1           1      55.353599  ...               0             2
2           2     103.991908  ...               1             3
3           3     198.984191  ...               0             4
4           4     144.626803  ...               0             4

[5 rows x 6 columns]

In [5]:
df.drop(columns=['Unnamed: 0'],inplace=True)

In [6]:
df.head()

   Rainfall (mm)  Temperature (°C)  Humidity (%)  Flood Occurred  Risk_encoded
0     218.999493         34.144337     43.912963               1             4
1      55.353599         28.778774     27.585422               0             2
2     103.991908         43.934956     30.108738               1             3
3     198.984191         21.569354     34.453690               0             4
4     144.626803         32.635692     36.292267               0             4

In [8]:
X=df.drop(columns=["Risk_encoded"])
Y=df["Risk_encoded"]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=42)

4901    4
4375    4
6698    1
9805    4
1101    1
       ..
5734    3
5191    4
5390    2
860     3
7270    2
Name: Risk_encoded, Length: 7500, dtype: int64

In [12]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()

In [49]:
X_train_encoded=scalar.fit_transform(X_train)

In [50]:
X_test_encoded=scalar.transform(X_test)

In [51]:
from sklearn.linear_model import LogisticRegression
regressor=LogisticRegression(n_jobs=-1,multi_class='multinomial',solver='lbfgs')

In [52]:
regressor.fit(X_train_encoded,Y_train)

e:\flood_risk_Alert\env\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

LogisticRegression(multi_class='multinomial', n_jobs=-1)

In [54]:
y_pred=regressor.predict(X_test_encoded)

In [55]:
from sklearn.metrics import accuracy_score

In [56]:
accuracy=accuracy_score(y_pred,Y_test)

In [57]:
accuracy

0.9664

In [58]:
from sklearn.neighbors import KNeighborsClassifier

In [62]:
best_accuracy = 0
best_k = 0
for k in range(1, 20):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_encoded, Y_train)
    y_pred = knn.predict(X_test_encoded)
    accuracy = accuracy_score(Y_test, y_pred)
    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_k = k

print(f'Best K: {best_k} with Accuracy: {best_accuracy}')

Best K: 1 with Accuracy: 0.93

In [63]:
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train_encoded, Y_train)
y_pred=knn.predict(X_test_encoded)

In [64]:
accuracy_knn=accuracy_score(y_pred,Y_test)

In [65]:
accuracy_knn

0.924

In [67]:
from sklearn.svm import SVC

svm = SVC(kernel='rbf') 
svm.fit(X_train_encoded, Y_train)
y_pred_svm = svm.predict(X_test_encoded)
accuracy_svm = accuracy_score(Y_test, y_pred_svm)
print("SVM Accuracy:", accuracy_svm)

SVM Accuracy: 0.9564

In [69]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

lr = LogisticRegression()

cv_scores_lr = cross_val_score(lr, X_train_encoded, Y_train, cv=5, scoring='accuracy')

print("Logistic Regression Cross-Validation Scores:", cv_scores_lr)
print("Mean Cross-Validation Accuracy:", cv_scores_lr.mean())

Logistic Regression Cross-Validation Scores: [0.96466667 0.96533333 0.96533333 0.96       0.96733333]
Mean Cross-Validation Accuracy: 0.9645333333333334

In [68]:
import pickle

In [73]:
with open('lr_model.pkl', 'wb') as f:
    pickle.dump(lr, f)

In [74]:
with open('scalar.pkl','wb') as f:
    pickle.dump(scalar,f)